      PROGRAM DAY9 PART1
      TYPE KNOT
        INTEGER X, Y
      END TYPE KNOT

      TYPE(KNOT) HEAD

      PARAMETER (MAPSIZE = 1024)
      INTEGER MAP(MAPSIZE, MAPSIZE), I, J

C INITIALIZE MAP
      DO 10 I = 1, MAPSIZE
        DO 20 J = 1, MAPSIZE
          MAP(I, J) = 0
   20   CONTINUE
   10 CONTINUE

C INITIALIZE HEAD IN THE CENTER OF THE MAP
      HEAD%X = MAPSIZE / 2
      HEAD%Y = HEAD%X

      STOP
      END
