#!/usr/bin/env bash
set -eu

script_dir=$(dirname $0)

print_help() {
    echo usage: lang [-s LANGUAGE] [-h]
    echo Shell options:
    echo   -h  print this message
    echo   -s  set the current language
}

load_options() {
    while getopts :hs: flag
    do
        case "${flag}" in
            s) echo $OPTARG > $script_dir/current-language;;
            h) print_help;;
            *) print_help; exit 1;;
        esac
    done
}

[[ $# != 0 ]] && load_options "$@" || cat $script_dir/current-language

